### ISSUE TITLE
[Proposal] Refactor `generate_sae_table.py` and `pretrained_sae_loaders.py` to share code

### ISSUE THREAD

**Issue by chanind** [jbloomAus/SAELens#305]
### Proposal 

Currently, the converters in `pretrained_sae_loaders.py` cannot be used in `generate_sae_table.py` because they return both a config file and the full SAE. As a result, we need to remember to manually re-create a lot of the functionality of the converters in `generate_sae_table.py` every time we add a new converter, and it's easy to forget / have these code paths be subtly different.

We should refactor the converter interface so there's a way to return only the config so that `generate_sae_table.py` can use the same converter code path as in `pretrained_sae_loaders`, and we don't need to manually duplicate code between these two files.

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/jbloomAus/SAELens/issues) in the repo (**required**)

**Comment by anthonyduong9** [comment]
@chanind I was looking at this issue and made [some changes](https://github.com/jbloomAus/SAELens/compare/main...anthonyduong9:SAELens:dedupe-code-to-get-config?expand=1) which I think might be better than changes to the `PretrainedSaeLoader` interface. Basically, they make it so that each `loader` function calls a `get` function, which takes a `repo_id: str` and `folder_name: str`, and then `generate_sae_table()` just calls these `get` functions to get the configs. The changes were easy to make since it followed what people had started to do, and also I think the changes to `PretrainedSaeLoader` would mean two of the three returns args are `Optional` and are often ignored (`_`), which seems like a code smell.

Please let me know what me know what you think! I can open a PR either way.

**Comment by chanind** [comment]
Sorry for the slow reply! This looks like it's on the right track. I was hoping as well that we could have a function that can load the config given the `model_info` and will internally figure out the correct conversion function to use to do that, e.g. `get_sae_config(model_info)`, so that function could be called both in the `pretrained_sae_loaders` and in `generate_sae_table` so we don't need to remember to add another if-statement into `generate_sae_table` everytime we add a new SAE converter; it would be great if that just happens for free. Otherwise, the changes in your diff look like they're moving in that direction, or could at least easily become what I'm talking about.
