### ISSUE TITLE
[Proposal] Move to version 1.0.0 to fix projects that depend on SAELens using caret ^ with semver

### ISSUE THREAD

**Issue by hijohnnylin** [jbloomAus/SAELens#98]
### Proposal 

Move the version number to 1.0.0. This does not propose any code changes.

### Motivation

`sae_vis` depends on `saelens` and uses caret notation `^0.5.0` to pick up SAELens. However, SAELens is now 0.6.0 and it is not picking up 0.6.0. This is because the caret works differently for projects that are lower than v1.0.0 - the caret will allow only 0.5.0 to 0.5.x, not anything 0.6.0 or above.
This means that sae_vis and other projects that depend on SAELens will not pick up 0.6.0 and later unless they specifically update their package dependency version to `^0.6.0`.

### Pitch

Move the version number to 1.0.0, and use the convention of major.minor.patch where MAJOR = backward incompatible changes, MINOR = backward compatible feature updates, PATCH = backward compatible fixes.

### Alternatives

An alternative is to stick with version <1.0.0, but make sure that:
- In an update from v0.x.y to v0.x+1.y, ensure that this is actually a backward incompatible change. Otherwise update it to v0.x.y to v0.x.y+1 instead.
- Document what the backward incompatible change is when v0.x.y is updated to v0.x+1.y

### Additional context

Additional context [here](https://nodesource.com/blog/semver-tilde-and-caret/) (it's on a node blog but semver works the same way), which addresses the debate in general.

The main reason to not move to 1.0.0 is that the maintainer may not think it's "finished" or "ready enough" in a way that others might think a 1.0.0 might require. This is pretty subjective, I leave that up to the maintainers to decide this. I think at the very least, we should do the alternative mentioned above.

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/jbloomAus/SAELens/issues) in the repo (**required**)

**Comment by chanind** [comment]
I'd support releasing 1.0.0 and just being diligent about bumping the major version whenever there's a breaking change. That could mean a lot of major version bumps potentially, but just being ruthless and unsentimental about using the major/minor/patch versioning to signal upgrade compatibility is one of the points of semantic versioning anyway. Having code in the pre-1.0.0 state feels confusing since it's less clear if a minor version means a breaking change or not. I guess being pre-1.0.0 is basically declaring the code to be unstable, but it's sort of a cop-out imo and we should just use semantic versions to communicate clearly.

As a side note, it seems troubling that `sae_vis` depends on `SAELens`, since `SAELens` also depends on `sae_vis`. Are there any issues with circular dependencies between projects like this?

**Comment by chanind** [comment]
note: added an issue to sae_vis for the circular dependency issue https://github.com/callummcdougall/sae_vis/issues/42

**Comment by hijohnnylin** [comment]
i noticed that python-semantic-release is now bumping the second number in the version when a "feat:" is committed, so anyone including saelens as a package won't pick up the new version (even though it's backward compatible) unless they manually change their pyproject. this makes me a little hesitant to use "feat:" because i don't want to make each release force other people to immediately be on outdated saelens.

it seems like the maintainers of that library feel strongly about starting packages at 1.0.0 according to this discussion: https://github.com/semantic-release/semantic-release/issues/1507

do we have agreement to bump to 1.0.0? i don't want to force a decision since it's a subjective call, but in the meantime i'll avoid using "feat" in the commit messages.

**Comment by chanind** [comment]
I just pushed an empty commit to bump to v1.0.0, seems like the right thing to do 👍
